num = input("coloque aqui os numeros que vc quiser caralho :")
nume = ' '.join(num)
nume = nume.split()
#print("Eis aqui pra vc mero mortal, os numeros que vc pediu separados : {}, {}, {}, {} e {}".format(nume[0],nume[1],nume[2],nume[3],nume[4]))
print("Analisando o numero :",num)
print("Unidades :",nume[4])
print("Dezenas :",nume[3])
print("Centenas :",nume[2])
print("Milhar :",nume[1])
print("Dmilhar :",nume[0])